### ISSUE TITLE
The current node list is empty

### ISSUE THREAD

**Issue by theomartiz** [loevgaard/trustpilot-scraper#1]
Hello ! 

I have tried to use the library, but when I launch the example I get the following error:

`Fatal error: Uncaught InvalidArgumentException: The current node list is empty. thrown in Scrapper/vendor/symfony/dom-crawler/Crawler.php on line 550`

Do you know this issue ?

Thanks in advance

**Comment by loevgaard** [comment]
Hi @theomartiz 

This repository isn't active at the moment. Feel free to submit a PR that fixes it :)
